### ISSUE TITLE
The file name is wrong after downloading a image/pdf/pptx/mp4 from google drive

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#1258]
Step:
 1. Launch Rocket
 2. Go to Google drive
 3. Download a file (.png/pdf/pptx/mp4)

Actual Result:
 - The downloading file with a wrong file name
 - Video1: https://youtu.be/VI347ocO5kg 
 - Video2: https://youtu.be/c0t9t0f9lfU
 - This issue can be reproduced on Redmi 4A and Sony Z3C.

Chrome & UC Result:
 - The downloading file with a right file name
 - UC Video: https://youtu.be/6J9gQAqj1CI 

Reproduction rate: 10/10
Rocket version: 1.0.1710
======================================
Device name: Redmi 4A
Android version: 6.0.1 MMB29M

Device name: Sony Z3C
Android version: 5.0.2 MMB29M

**Comment by mTwTm** [comment]
Root cause:
1. There is some contentDisposition for Google Drive files, such as: attachment;filename="FB_IMG_1487725024646.jpg";filename*=UTF-8''FB_IMG_1487725024646.jpg
However, the webview `parseContentDisposition` does not recognize this pattern:
`"attachment;\s*filename\s*=\s*("?)([^"]*)\1\s*$"`
so we did not get a well-formed fileName here.
2. Google drive is randomizing its url in a `https://doc-0c-5k-docs.googleusercontent.com/docs/securesc/41h4dghpgnkbqlui88cehqv94e3560i4/8tbbah0bedg4360mdb2hoqs4rgl87fvf/1512381600000/15594594420631511847/15594594420631511847/0B_uYkDofilrna2FJOWV2dTJZelE?e=download` format, so we guess it as part of the url.
