### ISSUE TITLE
Some svg files can't be downloaded correctly

### ISSUE THREAD

**Issue by dakaizou** [mozilla-mobile/FirefoxLite#1278]
STR:
 1. Visit [mozilla.org](https://www.mozilla.org)
 2. Slide down to see the cute dinosaur
 3. Download the dinosaur
 4. Open the dinosuar

Expected Result:
 - The dinosaur is opened
 - Chrome recording: https://drive.google.com/open?id=18VmCptH7hvYet5vVCc0Howl8SxFvpQeF

Actual Result:
 - The dinosuar is missing
 - Rocket recording: https://drive.google.com/open?id=1I_RKAsAo4MbF9UMiw8ynwiehkvwFCHf1

Reproduction rate: 5/5
Rocket version: 1.0.1 Build 1777

Device name: Samsung S7 edge
Android version: 7.0

Device name: Redmi 4A
Android version: 6.0

Related to #188, #699

**Comment by chianger** [comment]
Downloading is a common use case so P1.

**Comment by idiotmax** [comment]
The SVG file downloaded correctly, the display problem is on the viewer side. Chrome intercept ".svg" file extension, so they display it in Chrome themselves correctly. We ask system SVG viewer to handle it, and most of them handle it badly. The problem is not in our download function, suggest intercept ".svg" and handle file display ourselves if possible.

**Comment by NashTung** [comment]
This issue can be reproduced and as mxlius said, not download function incorrectly, just Rocket APP support it or not to display.

The Gallery or viewer picture app original on MIUI system does not support ".svg" file.

Video:
https://drive.google.com/open?id=12LZxhfn_qzidC-dGNcc_dhLJjwjVpkft

Device: Redmi 4A
Rocket: 2.0.0(4168).nightly
Android: 7.1.2
Android Webview: 66.0.3359.126
