### ISSUE TITLE
Favicons on the Bookmark list panel are all the same

### ISSUE THREAD

**Issue by cynthiatang** [mozilla-mobile/FirefoxLite#2121]
Issued by 

1. Launch Rocket
2. Add some bookmarks
3. Go to the bookmark panel

Actual Result: Those are not really favicons

Expected Result: There are really favicons

All devices
Rocket 2.2.0(5257).nightly

**Comment by ariefbayu** [comment]
may I try tackle this issue?

**Comment by mTwTm** [comment]
Sure! Here's some context to what's happening here:

We really like to first introduce bookmark in 2.3 so we've P2ed (P2 is to set a function/issue to non-blocking priority, see issue labels) favicon and shipped 2.3 with no favicons. It'd be great if you can help to work on this.

I'd also like to add some discussions we've made among engineers so far: We have favicon in: "Topsites", "History" and "Tabtray". Topsite and history are methodology1 and tabtray is methodology2. We'd really like to sync all these items to avoid duplicated storage consumption and inconsistency. If possible, we'd like to have an ultimate Favicon controller so each time we ask for a favicon we can simply get from it. This may take a lot of work, so another route is to only add favicon in Bookmarks with Tabtray's methodology. (methodology2 is preferred over methodology1.) My first thoughts are a first draft with methodology2 is acceptable but other engineers may think otherwise.

Feel free to also take a look at all those "P2" items since this label somewhat means things we'd like to fix but don't have time yet.

**Comment by ariefbayu** [comment]
I've comb through the codes. By methodology2, did you mean implementing code like this?

**
[loadCachedFavicon(tab, holder);](https://github.com/mozilla-tw/Rocket/blob/68014eb4345c205ed8d73cde9b46c1fefce9d8b2/app/src/main/java/org/mozilla/focus/tabs/tabtray/TabTrayAdapter.java#L138)
**

**Comment by mTwTm** [comment]
Yes! I think using that FaviconModel is sufficient and we shall have the Favicon shared because it's cached through url path. @pharspher would you like to add anything?

**Comment by mTwTm** [comment]
Now that in https://github.com/mozilla-tw/Rocket/pull/2465 we've simplified the logic of favicons used in History, it should be easier to use these directly in bookmarks too. We should take special care with the lifecycle of histories, bookmarks, though. In the long-term I still hope that we can migrate to something like [the places system](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Places) so we can separate history and a place (metadata of a site like icons)

**Comment by mTwTm** [comment]
[place](url)
