### ISSUE TITLE
Add idling Resource for TakescreenshotTest

### ISSUE THREAD

**Issue by cnevinc** [mozilla-mobile/FirefoxLite#2530]
Error log
https://app.bitrise.io/build/9090912738bb7cec

See https://github.com/mozilla-tw/Rocket/pull/2529

**Comment by josephyu1110** [comment]
Clarify that the root cause of test failed is due to my shots icon is missing. Per discussion with Nevin, we will leave this issue to add a new IdlingResource when delete the screenshot file.
<img width="1220" alt="screen shot 2018-09-04 at 11 30 02 am" src="https://user-images.githubusercontent.com/16300853/45009037-7efd8080-b038-11e8-83e0-e24384e17c22.png">
