### ISSUE TITLE
(meta) tab session refactor (dependency of #2537 multitab)

### ISSUE THREAD

**Issue by chianger** [mozilla-mobile/FirefoxLite#3006]
There are multiple WIP pull requests regarding refactoring around tab sessions. 
This refactor also eases the use of android component.

**Comment by chianger** [comment]
include #3008

**Comment by cnevinc** [comment]
I've spent some time in this sprint for this(2-3 days).
I've looked at AC's and our(Lite)'s code base and try to narrow down the scope and make an estimation on schedule for this task.

To let us use GeckoView, there are at least three things to complete:
1. Replace our session implementation to AC's browser-session module.
2. Make WebkitView implement AC's concept-engine module, or look at how focus-android uses GeckoView
3. Hook them up in SessionManager.

To use features directly from AC, we'll need more:
4. Use AC's Session Manager and feature-session module 
5. Use AC's browser-engine-gecko to interact with engine

For (1), we had a WIP PR https://github.com/mozilla-tw/Rocket/pull/3003. though it's not completed.
For (2), I haven't deeply looked at it yet.

Step 1~3 will take 3-4 weeks to implement (including fixing all Unit Test and add Integration Test).
Step 4~5 will need longer discussion.

**Comment by cnevinc** [comment]
Turns out Focus uses IWebViewProvider to provide different IWebView implementation. [see](https://github.com/cnevinc/focus-android/blob/a999b406d5971172591908a1bd9bf55f24f3afb0/app/src/main/java/org/mozilla/focus/web/WebViewProvider.kt#L21)
And it didn't use concept-engine at all. [see](https://github.com/cnevinc/focus-android/blob/a97f4eb4d9a9ce8c3373401f8b24d27faf1df569/app/src/main/java/org/mozilla/focus/Components.kt#L28)
Question: Since TabView is similar to IWebView for the same purpose, can we use GeckoView now?

Maybe I can come out with an estimation for both situations tomorrow or later.

**Comment by chianger** [comment]
this refactoring work will be mainly for #2537 so should be worked on all together.
