### ISSUE TITLE
Download manager enhancement v3 (pause/resume)

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#3044]
as a user, I want to be able to pause and resume my downloads

**Comment by suryaanshm** [comment]
@joechengla  could you provide an update on the current situation with this issue? I would like to contribute. Also, since this was a proposed project by Mozilla for GSoC 2019, under the title **"An Android file downloader designed for Emerging Markets"**, is this project also expected to be included in the proposed list of projects for GSoC 2020?
