### ISSUE TITLE
History is not inserting

### ISSUE THREAD

**Issue by mTwTm** [mozilla-mobile/FirefoxLite#3273]
**Describe the bug**
Some history is missing

**Steps To Reproduce**
1. Go to Youtube
2. Click on a suggested video
3. Check history

**Expected behavior**
The clicked video is in history

**Actual behavior**
The clicked video is not in history

**Device info (please complete the following information):**
My preliminary study suggests this is a Webview version based regression.

**Comment by Daisy-pliu** [comment]
Not happened on `Wikipedia`,`Ebay`
But happened on `Youtube`,`Instagram`,`Shopee`,`Facebook`,`Reddit`
add this special case to [TC0203](https://docs.google.com/spreadsheets/d/1AJZaeNDln6TJWjoilB3oz9AYpVkCTCkH4tXoo9oJMz8/edit?ts=5bea38ae#gid=169764628&range=B314)
Test device: Pixel 2 (9.0)
Test version : 1.1.4 (10373)
Webview: 72.0.3626.121

**Comment by chianger** [comment]
This issue existed much longer than I expected.
I picked previous releases since Firefox Lite 1.0.0 and those are all impacted.
Firefox Rocket 3.2.0 until Firefox Lite 1.0.0 has issue #2930 so there's no youtube history as well.
Most importantly, Rocket v3.1.0 wasn't impacted by #2930 (meaning there's correct YouTube link on the URL bar) but still, the history panel shows m.youtube.com.

**Comment by josephyu1110** [comment]
Browsing history's insertion starts [here](https://github.com/mozilla-tw/FirefoxLite/blob/30fb8dacfe19bd2c6be1775200f950c98bd6fc68/app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.java#L1085). From my investigation, onLoadingStateChanged() is called only once from STR.
