### ISSUE TITLE
Unable to clear error icon on menu button to access menu 

### ISSUE THREAD

**Issue by joechengla** [mozilla-mobile/FirefoxLite#3524]
**Describe the bug**
Unable to clear ! on "..." button to access menu even after having successful downloads

**Steps To Reproduce**
No reproduce steps. Noticed the symptom after some time. Cannot recall what I did earlier.

**Screenshots/videos**
https://drive.google.com/file/d/1d90_9_l25_igbGLZ_AynF_TTUr5BYpTN/view?usp=sharing

**Device info (please complete the following information):**
 - Device: Pixel 3
 - OS:  Android 9
 - Webview 73.0.3683.90
 - Version 1.4.0 (11337)

**Comment by chianger** [comment]
No concrete STR yet. QAWanted to try out.

**Comment by Daisy-pliu** [comment]
**test step:**
1. launch app
2. search [https://downloadfiletest-eab8a.firebaseapp.com/]
3. tap [50MB] 
4. cut off network  
5. kill and relaunch app
6. long tap [downloads]->tap [back] -> user should see [error icon]
7. long click [menu]
8. tap [more] -> [remove from list] on this download failed file
9 connect to network 
10. tap [5MB ] 

**Actual result:**
see [error icon] even download success

**Expect result:**
not see [error icon] even download success

**Device**
samsung 8.0 , advan 5.0


**Note:**
if on step 6 user tap [delete file] , instead of [remove from list], this issue will not happen.

**Comment by chianger** [comment]
S1 given above STR showing there's a chance that user not able to recover from seeing the ! icon.
