### ISSUE TITLE
If the slidebar of Nightmode is on the screen, landscape mode displayed incorrect

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#3578]
**Describe the bug**
If you turn to landscape mode with night mode slidebar, the display is incorrect

**Steps To Reproduce**
1. Launch Firefox Lite and go to a web page
2. Click on menu, and then select night mode
3. turn the device into landscape mode

**Expected behavior**
web page is displayed in landscape mode with full screen

**Actual behavior**
the web page remain the same width with black on the right.

**Screenshots/videos**
![Screenshot_20190510-140450](https://user-images.githubusercontent.com/1625148/57506089-577c5780-732d-11e9-97a1-58c8a1b7f3e2.png)

**Device info (please complete the following information):**
 - Device: hTC U11
 - OS: Android 8.0
 - Webview 74.0.3729.136
 - Version 1.5.1 (11964)

**Reproduce rate**
5/5

**Additional context**

**Comment by Conjuror** [comment]
The same in other OS version

**Comment by pharspher** [comment]
The night mode slidebar is implemented using a transparent activity, which is forbidden to lock screen orientation after api level 26, so we can't lock the screen to portrait. Also because it's an activity, once it is shown the browser was sent to the background and are unable to update the web view.

To solve this issue, we may need some time to rework this dialog.
