### ISSUE TITLE
[Travel] Spike for KKday API

### ISSUE THREAD

**Issue by tinahsieh** [mozilla-mobile/FirefoxLite#4563]
As we've gotten more information about the KKday API, we'll need a spike for understanding the feasibility.

**Comment by cnevinc** [comment]
Roughly look through the document.
1. We haven't got the API key yet?
2. The data format (language/city...etc) is not compatible with current data from Booking.com. We'll need to do some mapping before we can implement it.
3. Suggest putting this kind of integration logic in backend. Otherwise, every time we have a new vendor, we'll need to release a new version so that the users can see it.
