### ISSUE TITLE
Notification Research: token collection

### ISSUE THREAD

**Issue by shsu571** [mozilla-mobile/FirefoxLite#4598]
Spec detail: https://docs.google.com/presentation/d/16WM3bb7dWLnxx4f92gU4q9FbReXljvSZmYw6RSdwJRk/edit#slide=id.g7c04d34df7_1_6
Spec detail for this issue

- Confirm how to get token from users
- how to get users id (the same user idea of telemetry)
**still wait for policy team to confirm we can collect token ides or not**

User case:
MSRP
As a user, I want to be notified in time when there’s challenge start. Data: Backend
As a user, I would like to be reminded when I forgot to finish today’s challenge action. Data: Backend
As a user, I would like to be reminded that I finished the challenge and I need to go to redeem to get the prize.  Data: Backend
As a user, I would like to be reminded that I got the voucher but I haven’t redeem and it’s going to expire soon.  Data: Backend
Vertical or new feature
As a user, I would like to be reminded that Firefox Lite launched new feature.
Users: who never uses the new feature or vertical Data: Telemetry
Purpose: Increase new user's interesting to try new feature or vertical
As a user, I would like to be notified that Firefox Lite news vertical provides latest news content.
Users: who visited news vertical before  Data: Telemetry
Purpose: Increase user's interesting vertical engagement
As a user, I would like to be notified that Firefox Lite game vertical provides new game now.
Users: who visited game vertical before  Data: Telemetry
Purpose: Increase user's interesting vertical engagement
As a user, I would like to be notified that Firefox Lite shopping vertical provides today’s best deal/coupons.
Users: who visited shopping vertical before Data: Telemetry
Purpose: Increase user's interesting vertical engagement
Overall
As a user, I can be notified more features I can try when I installed app after x days
As a product manager, I want to notify users with Image Notification when they haven’t use the app for a long time.

**Comment by Conjuror** [comment]
Add **need crossfunctional** as we are waiting for approval from policy team

**Comment by cnevinc** [comment]
Data Questions

Why do we need a token?
The token is generated by Firebase Cloud Messaging SDK when the user launch the app. We need this token to communicate(send messages) to the users.

Previously we sent messages from Firebase Admin console ( Firebase server -> Apps)
Now we want to send messages from our server ( Our server -> Firebase server -> Apps)
That’s why we need to collect the token from the APP to our server
What does the user token contain? 
A random string like this 
c3jJHLgli18:APA91bHuhLlWe0RUK9IFe9PBtGZrha8c-Q4nSOI8Yy2mJZTk9JP0Nc-jd7egXIy_-XR0-XhXes08VqyrBpB5UCKd6SAzFRkfqX4KGgUTe6DG8MMn7wvJDTdSq0mLmScpjA-3eDN3xLzN
The token seems to be single use, but please confirm. 
The token will be re-generated by Firebase SDK. So we may need to update this id to our server every time it’s regenerated. Also, we need this ID every time when we send messages from our server to FCM server.
Is the User ID the same as Client ID? ???
are you combining this with the telemetry id?   YES


How does this work with FxA?  
It won’t work with FxA
Does this require the collection of the FxA client ID?  
NO
What information is being collected in order to send a message?
Telemetry client id. Since we need to map the telemetry user with the Firebase Cloud Messaging SDK
Will the opt-out mechanism for data collection/messages be the same as it currently works for sending data to Firebase? (via “Send Usage Data” settings)
YES
Firebase & Code Questions

Are you planning on discontinuing Firebase if we go with a Mozilla server method?
NO
Why does it take 24 hours to collect audience information?
User audience can use user properties for segmentation. Since user properties are not updated in real time, it may take several hours(sometimes ~ 24 hours) to update. See  https://firebase.google.com/docs/analytics/user-properties?platform=android
Are we writing the replacement code ourselves? NO
Is it open source? YES WE OPEN SOURCE OUR BACKEND CODE
Are we getting rid of all the closed source code that was in FxLite? NO. ONLY THE FIREBASE SDK IS CLOSED SOURCE. WE STILL USE IT( AND DIDN”T ADD ANY NEW SDK)


Messages

How are the messages that are being planned in the user cases different than what is currently pushed out via Firebase?  
In current design, we can only send push notification in Firebase’s admin console. There’s no server-related information(MSRP, Verticals) in Firebase console.
In current design, we can’t send the notifiotion with images when the user didn’t open our app. See https://firebase.google.com/docs/cloud-messaging/concept-options#data_messages
What messages do we want to send? <PM> 
Is is the same as the messages we’re sending now?<PM>
What type of reporting will be available to product and marketing teams about user engagement?  
Will any of the reporting include user ids?
Are you planning to create user profiles with messaging engagement measurements?  NOT NOW??

**Comment by shsu571** [comment]
Notes: 
Max needs to confirm 
-Firefox account + token + anonymous id will not be anonymous
-How can  users ask us to stop notification?
