### ISSUE TITLE
Unable to download PDF files on certain site (https://kemenkeu.go.id/covid19)

### ISSUE THREAD

**Issue by ariefbayu** [mozilla-mobile/FirefoxLite#4869]
**Describe the bug**
Downloading PDF files from this sites result in error (paused message, in download list) while the same procedure result success in chrome.

**Steps To Reproduce**
1. Go to 'https://kemenkeu.go.id/covid19'
2. Click on 'Lampiran Perpres No. 54 Tahun 2O2O'
3. Download should started
4. See error in download page

**Expected behavior**
Download should happened

**Actual behavior**
Download was failed

**Screenshots/videos**
![video-2020-04-07-18-34-32](https://user-images.githubusercontent.com/55084/78664836-00954e80-78ff-11ea-91b6-7ecec48d6fc1.gif)

**Device info (please complete the following information):**
 - Device: Xiaomi Mi A1
 - OS: 9 Security Patch Match 1, 2020
 - Webview: 80.0.3987.162
 - Version: 2.1.13(19164)

**Reproduce rate**
Reproduced everytime

**Additional context**

**Comment by benjamin-cheng** [comment]
Thanks @ariefbayu reporting this issue. I have initial finding about it.
The pdf file from specific site cannot be downloaded successfully due to that the SSL certificate is not installed properly on server side, and Firefox Lite doesn't have the error handling flow to force downloading file when there is a SSL certificate problem. I'll report it to PM team to see if there is any improvement for the issue.

How I found the SSL certificate issue:
1. Check the server by SSL checker service and get warning message like:
`The certificate is not trusted in all web browsers. You may need to install an Intermediate/chain certificate to link it to a trusted root certificate.`
2. The warning log from Android native download manager:
`W/DownloadManager: [2074] Stop requested with status HTTP_DATA_ERROR: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`
