### ISSUE TITLE
Colors of Visited link didn't align browsing behavior

### ISSUE THREAD

**Issue by Conjuror** [mozilla-mobile/FirefoxLite#698]
Currently, visited link didn't work well.

Following STR works as expected:

Build: 887
STR:

1. Launch Zerda
2. Search "Squash" with Google (it should be the same with any search engine)
3. Tap on a suggested result link
4. Press system back key and refresh the page

Expected Result:

4. The clicked link is shown as purple

Actual Result:

4. The clicked link is shown as purple

However, when you exit the app and search for "Squash" again. The clicked link doesn't change its color. 

Also, if you attempt to clear browsing history(history, cache, cookie), it doesn't change the link color from purple to blue.

On Google Chrome app, if you clear browsing history, the link changes its color to blue.

**Comment by pocmo** [comment]
Might be related: https://github.com/mozilla-mobile/focus-android/issues/828

**Comment by pocmo** [comment]
As well as: https://github.com/mozilla-mobile/focus-android/issues/1220

**Comment by chianger** [comment]
likely a webview limitation

**Comment by ukpw** [comment]
Hi

This is still evident in the latest Nightly build (0.8.1443.nightly).  Steps taken to find/replicate:

(Found on, and confirmed on, an Android 5.1 device with Chrome and Android System WebView disabled.)

1. Clear the app data (to set Zerda to default settings).
2. Search for "bbc news".
3. Select the first link (under top stories).
4. Wait for page to open.
5. Press the "home" icon.
6. Press the settings icon, then "Clear cache".
7. Search for "bbc news".
8. Select the first link (under top stories).

The link colour should be blue (for unopened) but will display as purple (as a link what had been visited previously), even though the history has been cleared,

Further to work I was involved in earlier this year with pocmo, I belive that this issue is caused by a flaw in Android WebView that could be partly mitigated by pocmo's magic fix.  It will not solve the underlying issue, but it will make it a bit more bearable.

**Comment by chianger** [comment]
Stays at P2 per triage. There are many other P1s to be taken at this moment, and this issue is more on WebView itself.

**Comment by chianger** [comment]
considering "clear browsing history" as malfunction so put it to s1.
need UX to define.
