### ISSUE TITLE
File name/time in Downloads becomes unknown

### ISSUE THREAD

**Issue by cssjh** [mozilla-mobile/FirefoxLite#799]
**STR**
1. Download a file
2. Delete its record in Samsung system download history (the file itself still exists)
3. Open Downloads panel -> the file's name and size/time will be unknown

**DuT:** Samsung
**Build:** 1050

**Comment by mTwTm** [comment]
The current architecture rely on the download manager's record to gather values. To store it our self would require a pretty big architecture change. (We would need to collect these entries in an schema-updated database and need to handle other things that happens when our app is not active.) My opinion on this is this may need to postpone until Zerda 2.0

**Comment by NashTung** [comment]
It can be reproduced
Video: https://drive.google.com/open?id=1VNXkf1T5Agkj-qh-gozJn4Ql3I1juoA0

Device: Redmi 4A
Rocket: 2.1.0(4512).nightly
Android: 7.1.2
Android Webview: 66.0.3359.158
